GET http://localhost:5144/api/dictionary/dog
###

POST http://localhost:5144/api/dictionary/add?englishWord=moon&translation=луна&memorizationLevel=2
###

GET http://localhost:5144/api/dictionary/baby
###

GET http://localhost:5144/api/dictionary/test
###

DELETE http://localhost:5144/api/dictionary/moon
###

