GET http://localhost:5144/api/dictionary/1
###

POST http://localhost:5144/api/dictionary/add?englishWord=dog&translation=собака&memorizationLevel=1
###

POST http://localhost:5144/api/dictionary/add?englishWord=friend&translation=друг&memorizationLevel=1
###

GET http://localhost:5144/api/dictionary/test
###

POST http://localhost:5144/api/dictionary/add?englishWord=egg&translation=яйцо&memorizationLevel=1
###

POST http://localhost:5144/api/dictionary/add?englishWord=ITMO&translation=ИТМО&memorizationLevel=3
###

POST http://localhost:5144/api/dictionary/add?englishWord=programming&translation=программирование&memorizationLevel=3
###

GET http://localhost:5144/api/dictionary/8
###